- name: Setup HAProxy
  hosts: haproxy
  become: yes
  tasks:
  - name: Install HAProxy
    package:
      name: haproxy
      state: present
  - name: Enable haproxy service on boot
    systemd:
      name: haproxy
      enabled: yes
      state: started
  - name: Copy files from local to remote
    copy:
      src: /home/vagrant/ITToolsTask/plays/cert/webserverCert.pem
      dest: /etc/pki/tls/certs/webserverCert.pem
      owner: vagrant
      group: vagrant
      mode: '0644' 
    notify: 
      - Restart HAProxy
  - name: Copy files from local to remote
    copy:
      src: /home/vagrant/ITToolsTask/plays/CA/ca-certificate.crt
      dest: /etc/pki/CA/certs/ca-certificate.crt
      owner: vagrant
      group: vagrant
      mode: '0644'
    notify:
      - Restart HAProxy
  - name: Deploy HAProxy configuration
    template:
      src: haproxy.cfg.j2
      dest: /etc/haproxy/haproxy.cfg
    notify:
      - Restart HAProxy

  handlers:
    - name: Restart HAProxy
      service:
        name: haproxy
        state: restarted
