- name: Setup Keepalived
  hosts: haproxy
  become: yes
  tasks:
    - name: Install Keepalived
      yum:
        name: keepalived
        state: present
    - name: Enable keepalived service on boot
      systemd:
        name: keepalived
        enabled: yes
        state: started
    - name: Configure Keepalived
      template:
        src: keepalived.conf.j2
        dest: /etc/keepalived/keepalived.conf
      notify:
        - Restart Keepalived

    handlers:
      - name: Restart Keepalived
        service:
          name: keepalived
          state: restarted
