- name: Install httpd and config incoming traffic ports
  hosts: catfood_webservers:bighead_webservers
  become: true
  tasks:
  - name: Copy files from local to remote
    copy:
      src: /home/vagrant/ITToolsTask/plays/cert/webserverCert.key
      dest: /etc/pki/tls/private/webserverCert.key
      owner: vagrant
      group: vagrant
      mode: '0644'
    notify: restart httpd
  - name: Copy files from local to remote
    copy:
      src: /home/vagrant/ITToolsTask/plays/cert/webserverCert.crt
      dest: /etc/pki/tls/certs/webserverCert.crt
      owner: vagrant
      group: vagrant
      mode: '0644'
    notify: restart httpd
  - name: Install the mod_ssl package
    yum:
      name: mod_ssl
      state: present
  - name: Template a file to /var/www/html/index.html
    template:
      src: ssl.conf.j2
      dest: /etc/httpd/conf.d/ssl.conf
      owner: vagrant
      group: vagrant
    notify: restart httpd

  handlers:
    - name: restart httpd
      service:
        name: httpd
        state: restarted
